---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-cloudscale-appuio-io-v1beta1-loadbalancer
  failurePolicy: Fail
  name: validate-cloudscale-v1beta1-loadbalancer.appuio.io
  rules:
  - apiGroups:
    - cloudscale.appuio.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - loadbalancers
  sideEffects: None
