//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowedCIDR) DeepCopyInto(out *AllowedCIDR) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowedCIDR.
func (in *AllowedCIDR) DeepCopy() *AllowedCIDR {
	if in == nil {
		return nil
	}
	out := new(AllowedCIDR)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowedSubnet) DeepCopyInto(out *AllowedSubnet) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowedSubnet.
func (in *AllowedSubnet) DeepCopy() *AllowedSubnet {
	if in == nil {
		return nil
	}
	out := new(AllowedSubnet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FloatingIPAddress) DeepCopyInto(out *FloatingIPAddress) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FloatingIPAddress.
func (in *FloatingIPAddress) DeepCopy() *FloatingIPAddress {
	if in == nil {
		return nil
	}
	out := new(FloatingIPAddress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPHealthMonitor) DeepCopyInto(out *HTTPHealthMonitor) {
	*out = *in
	if in.StatusCodes != nil {
		in, out := &in.StatusCodes, &out.StatusCodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPHealthMonitor.
func (in *HTTPHealthMonitor) DeepCopy() *HTTPHealthMonitor {
	if in == nil {
		return nil
	}
	out := new(HTTPHealthMonitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthMonitor) DeepCopyInto(out *HealthMonitor) {
	*out = *in
	out.Delay = in.Delay
	out.Timeout = in.Timeout
	in.HTTP.DeepCopyInto(&out.HTTP)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthMonitor.
func (in *HealthMonitor) DeepCopy() *HealthMonitor {
	if in == nil {
		return nil
	}
	out := new(HealthMonitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancer) DeepCopyInto(out *LoadBalancer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancer.
func (in *LoadBalancer) DeepCopy() *LoadBalancer {
	if in == nil {
		return nil
	}
	out := new(LoadBalancer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerList) DeepCopyInto(out *LoadBalancerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LoadBalancer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerList.
func (in *LoadBalancerList) DeepCopy() *LoadBalancerList {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerSpec) DeepCopyInto(out *LoadBalancerSpec) {
	*out = *in
	if in.VirtualIPAddresses != nil {
		in, out := &in.VirtualIPAddresses, &out.VirtualIPAddresses
		*out = make([]VirtualIPAddress, len(*in))
		copy(*out, *in)
	}
	if in.FloatingIPAddresses != nil {
		in, out := &in.FloatingIPAddresses, &out.FloatingIPAddresses
		*out = make([]FloatingIPAddress, len(*in))
		copy(*out, *in)
	}
	if in.Pools != nil {
		in, out := &in.Pools, &out.Pools
		*out = make([]Pool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerSpec.
func (in *LoadBalancerSpec) DeepCopy() *LoadBalancerSpec {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerStatus) DeepCopyInto(out *LoadBalancerStatus) {
	*out = *in
	if in.VirtualIPAddresses != nil {
		in, out := &in.VirtualIPAddresses, &out.VirtualIPAddresses
		*out = make([]StatusVirtualIPAddress, len(*in))
		copy(*out, *in)
	}
	if in.FloatingIPAddresses != nil {
		in, out := &in.FloatingIPAddresses, &out.FloatingIPAddresses
		*out = make([]StatusFloatingIPAddress, len(*in))
		copy(*out, *in)
	}
	if in.Pools != nil {
		in, out := &in.Pools, &out.Pools
		*out = make([]StatusPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerStatus.
func (in *LoadBalancerStatus) DeepCopy() *LoadBalancerStatus {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Pool) DeepCopyInto(out *Pool) {
	*out = *in
	in.Frontend.DeepCopyInto(&out.Frontend)
	in.Backend.DeepCopyInto(&out.Backend)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Pool.
func (in *Pool) DeepCopy() *Pool {
	if in == nil {
		return nil
	}
	out := new(Pool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolBackend) DeepCopyInto(out *PoolBackend) {
	*out = *in
	in.HealthMonitor.DeepCopyInto(&out.HealthMonitor)
	in.NodeSelector.DeepCopyInto(&out.NodeSelector)
	out.DataTimeout = in.DataTimeout
	out.ConnectTimeout = in.ConnectTimeout
	if in.AllowedSubnets != nil {
		in, out := &in.AllowedSubnets, &out.AllowedSubnets
		*out = make([]AllowedSubnet, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolBackend.
func (in *PoolBackend) DeepCopy() *PoolBackend {
	if in == nil {
		return nil
	}
	out := new(PoolBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolFrontend) DeepCopyInto(out *PoolFrontend) {
	*out = *in
	if in.AllowedCIDRs != nil {
		in, out := &in.AllowedCIDRs, &out.AllowedCIDRs
		*out = make([]AllowedCIDR, len(*in))
		copy(*out, *in)
	}
	out.DataTimeout = in.DataTimeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolFrontend.
func (in *PoolFrontend) DeepCopy() *PoolFrontend {
	if in == nil {
		return nil
	}
	out := new(PoolFrontend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusBackend) DeepCopyInto(out *StatusBackend) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusBackend.
func (in *StatusBackend) DeepCopy() *StatusBackend {
	if in == nil {
		return nil
	}
	out := new(StatusBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusFloatingIPAddress) DeepCopyInto(out *StatusFloatingIPAddress) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusFloatingIPAddress.
func (in *StatusFloatingIPAddress) DeepCopy() *StatusFloatingIPAddress {
	if in == nil {
		return nil
	}
	out := new(StatusFloatingIPAddress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusPool) DeepCopyInto(out *StatusPool) {
	*out = *in
	if in.Backends != nil {
		in, out := &in.Backends, &out.Backends
		*out = make([]StatusBackend, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusPool.
func (in *StatusPool) DeepCopy() *StatusPool {
	if in == nil {
		return nil
	}
	out := new(StatusPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusVirtualIPAddress) DeepCopyInto(out *StatusVirtualIPAddress) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusVirtualIPAddress.
func (in *StatusVirtualIPAddress) DeepCopy() *StatusVirtualIPAddress {
	if in == nil {
		return nil
	}
	out := new(StatusVirtualIPAddress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualIPAddress) DeepCopyInto(out *VirtualIPAddress) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualIPAddress.
func (in *VirtualIPAddress) DeepCopy() *VirtualIPAddress {
	if in == nil {
		return nil
	}
	out := new(VirtualIPAddress)
	in.DeepCopyInto(out)
	return out
}
